# Generated by Django 2.2.7 on 2019-12-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20191212_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='imprant',
            new_name='imprint',
        ),
    ]
