# Generated by Django 2.2.7 on 2019-12-28 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['-due_back'], 'permissions': (('can_mark_returned', 'Set Book as returned'),)},
        ),
    ]
