# Generated by Django 2.2.7 on 2019-12-31 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20191228_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
